image: Visual Studio 2019
platform: amd64
version: '1.0.2.{build}'
build: off

install:
  - set QTDIR=C:\Qt\5.15.2\msvc2019_64
  - ls C:\Qt\Tools\QtInstallerFramework
  - set PATH=%PATH%;%QTDIR%
  - C:\Qt\5.15.2\msvc2019_64\bin\qtenv2.bat
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat %platform%
  - set makefiles="NMake Makefiles"

build_script:
  - cd C:\projects\SchoolKiosk
  - qmake KioskInstaller.pro
  - nmake

after_build:
  - cp C:\projects\InstallerRelease\Kiosk.offline.exe .
  - 7z a initFiles.zip C:\projects\SchoolKiosk\initFiles\* C:\projects\SchoolKiosk\Kiosk\settings.ini
  
artifacts:
  - path: Kiosk.offline.exe
  - path: initFiles.zip

deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: ''
  provider: GitHub
  auth_token:
    secure: FBpMGGqGNfo7d+81JLc5kdzQlpQ7KXiG2cdDx6AhR/s6bAoydRJMO0x1xwUB7apA # your encrypted token from GitHub
  artifact: Kiosk.offline.exe, initFiles.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false        # deploy on tag push only
